@host = http://localhost:8000 

GET {{host}}/hi HTTP/1.1
Content-Type: application/json

###

POST https://api.x.ai/v1/chat/completions HTTP/1.1
content-type: application/json
authorization: Bearer xai-o8dMAYvIy7a93dwvsIFZ6t42Hb4drfBnbnI7lznmbX1QPMGiRDtOuGZv3QfquwpG5JZtoFThx32Jfz6c

{
  "messages": [
    {
      "role": "system",
      "content": "You are a test assistant."
    },
    {
      "role": "user",
      "content": "Testing. Just say hi and hello world and nothing else."
    }
  ],
  "model": "grok-beta",
  "stream": false,
  "temperature": 0
}
